[#165145794] Implement Authentication Modal
andela/ah-legion-frontend pull request #11
Opened 2019-04-05 13:09 UTC by MandelaK

- Implement uniform authentication modal that can accept signup and login components

2019-04-09 07:33 UTC, MandelaK commented on src/components/Header.jsx
> +            <Nav.Item onClick={() => store.dispatch({type: LOGIN, payload: null})} className="nav-link auth-btn ">
Because we don't need to pass any payload, we can just pass the type only instead of passing a payload of null.

2019-04-09 07:34 UTC, MandelaK commented on src/components/Header.jsx
> +            <Nav.Item onClick={() => store.dispatch({type: REGISTER, payload: null})} className="nav-link auth-btn get-started">
No need of passing a payload of null, just pass the type only and exclude payload altogether, ie `dispatch({ type: REGISTER })`

2019-04-09 07:36 UTC, MandelaK commented on src/store/reducers/index.js
> +            return Object.assign({}, state, paylod);
Please fix the typo `paylod`

2019-04-09 07:38 UTC, MandelaK commented
Good job, the modal seems to be working, please fix the minor errors I have pointed out, let's rally the team to review this so we can finish the feature

2019-04-09 07:46 UTC, cob04 commented
I have tested it manually, and i think it works great.

2019-04-10 06:42 UTC, BrianSerem submitted a review, later dismissed
Unless you add more changes this is good to go.

2019-04-10 07:03 UTC, abulojoshua1 requested changes

2019-04-10 07:03 UTC, abulojoshua1 commented on src/components/AuthenticationModal.jsx
> +    modalShow: state.modalState.modalShow};
@MandelaK, kindly destructure state here.

2019-04-10 07:03 UTC, abulojoshua1 commented on src/components/AuthenticationModal.jsx
> +    let onHide = () => dispatch(showModal({modalShow: false}))
@MandelaK, use `const` instead of `let` when you will not change the value of a variable.

2019-04-10 07:03 UTC, abulojoshua1 commented on src/components/Header.jsx
> +import { LOGIN, REGISTER} from '../store/actions/action-types';
@MandelaK, kindly add space after `}` on this line.

2019-04-10 07:03 UTC, abulojoshua1 commented on src/css/App.css
> +/* Authentication modal*/
@MandelaK, remove this commented out code if it is not necessary.

2019-04-10 07:03 UTC, abulojoshua1 commented on src/css/App.css
> +  height: 600px;
@MandelaK, use percentages or other values for heights instead of pixels, pixels can act unpredictably on different screen sizes.

2019-04-10 07:03 UTC, abulojoshua1 commented on src/store/actions/action-types.js
> +export const LOGIN = 'LOGIN';
@MandelaK, add EOF here.

2019-04-10 07:03 UTC, abulojoshua1 commented on src/tests/components/AuthenticationModal.test.js
> +  it('div tag displays correctly in "debug" mode', () => {
@MandelaK, make the `it` block descriptive, use something like `it (' should blah blah blah..', () => {
})`

2019-04-10 07:03 UTC, abulojoshua1 commented on src/tests/components/AuthenticationModal.test.js
> +});
@MandelaK, also make sure the number of tests you write provides considerable test coverage for the code you have written.

2019-04-10 07:07 UTC, abulojoshua1 commented
@MandelaK, add more info on what the PR does.

2019-04-10 15:14 UTC, MandelaK commented on src/components/AuthenticationModal.jsx
> +    console.log(this.props)
remember to remove this `console.log` statement before it is merged

2019-04-10 15:14 UTC, MandelaK commented on src/store/actions/change-form-action.js
> +export function showModal(payload) {
Export this as `default`

2019-04-11 08:53 UTC, RachelleMaina approved these changes
Apart from the issues that had been pointed out and hound violations, which have been solved already, everything looks good to me

2019-04-11 13:01 UTC, MandelaK commented
Everything looks good to me ... Apparently since I am the one who opened this PR, I cannot approve it.

2019-04-11 13:03 UTC, Etomovich approved these changes

2019-04-11 13:32 UTC, ElMonstro approved these changes

2019-04-11 13:52 UTC, cob04 approved these changes
I have tested it manually and I find it satisfactory. I also like the API you have introduced it makes it easy to integrate social login.

2019-04-11 14:50 UTC, ElMonstro approved these changes

2019-04-11 14:50 UTC, ElMonstro commented on src/components/AuthenticationModal.jsx
> +    const { modalShow, dispatch, isRegister } = this.props;
I have used prop-types I don't know why it's displaying this

2019-04-11 14:58 UTC, abulojoshua1 requested changes

2019-04-11 14:58 UTC, abulojoshua1 commented on src/middleware/auth-modal-middleware.js
> +}
This file contains actions, kindly change place it in the actions directory and rename it to something line AuthActions.js

2019-04-11 15:02 UTC, abulojoshua1 commented
@ElMonstro, use camel case for js file naming. For example `CamelCase.js`

2019-04-12 07:30 UTC, abulojoshua1 approved these changes
LGTM

2019-04-12 07:30 UTC, merged