#164046214 Users can see list of articles
andela/ah-legion-frontend pull request #18
Opened 2019-04-12 07:12 UTC by RachelleMaina

### What does this PR do?
 -  Enable users to see list of articles in the application on the homepage
 -  add utils to get image from body and format db DateTime field
 -  styles homepage
 -  add utils tests

### Description
 -  add list article components, container, actions and actiontypes
 -  add utils to get image from body and format db DateTime field
 -  styles homepage
 -  add utils tests

### How has this been tested?
 - [x] Unit tests

### How to manually test this:
- Clone the repository `https://github.com/andela/ah-legion-frontend`
- Checkout the branch `ft-list-all-articles-164046214`
- Run `npm install` to install dependecies
-  Run `npm start' to fire up the dev server
-  Go to a browser and try visiting the home url ie. `/`

### PT
[#164046214](https://www.pivotaltracker.com/story/show/164046214)

2019-04-12 08:11 UTC, abulojoshua1 commented
@RachelleMaina, kindly fix the coverage drop.

2019-04-12 08:30 UTC, RachelleMaina commented
> @RachelleMaina, kindly fix the coverage drop.

Will do this.

2019-04-14 11:55 UTC, MandelaK commented on src/tests/axiosConfig.js
> +import axios from 'axios';
I think you already defined this module in `src/axiosConfig.js` so I don't see why you should do it again here. Unless you have a compelling reason, I'd advise you do away with this

2019-04-14 19:06 UTC, BrianSerem commented on src/axiosConfig.js
> +const BASE_URL = 'https://ah-legion-staging.herokuapp.com/api/';
This URL should be in the .env file.

2019-04-15 15:42 UTC, RachelleMaina commented
> @RachelleMaina, kindly fix the coverage drop.

It is all good now

2019-04-16 12:25 UTC, MandelaK reviewed
Just fix the linting errors, everything else looks good

2019-04-16 16:37 UTC, abulojoshua1 commented on src/containers/HomeView.jsx
> +  }
Kindly fix this.

2019-04-16 16:38 UTC, abulojoshua1 commented
@RachelleMaina, kindly fix the HoundCi comments.

2019-04-16 17:43 UTC, RachelleMaina commented
> @RachelleMaina, kindly fix the HoundCi comments.

I have fixed all of the comments except JsDoc Comments, I do not know why Hound is still capturing them.

2019-04-17 06:25 UTC, Etomovich approved these changes

2019-04-17 07:01 UTC, ElMonstro approved these changes
LGTM

2019-04-17 07:12 UTC, BrianSerem approved these changes

2019-04-17 07:22 UTC, MandelaK commented on src/containers/HomeView.jsx
> +export const mapStateToProps = state => ({ articles: state.articles });
Please destructure articles here 
```suggestion
export const mapStateToProps = state => ( const { articles } = state; { articles});
```

2019-04-17 07:24 UTC, MandelaK requested changes
Rachelle please untrack `package-lock.json` from this PR

2019-04-17 08:10 UTC, RachelleMaina commented on src/containers/HomeView.jsx
> +export const mapStateToProps = state => ({ articles: state.articles });
Will do this.

2019-04-17 08:21 UTC, MandelaK approved these changes

2019-04-17 12:31 UTC, abulojoshua1 approved these changes
LGTM

2019-04-17 12:31 UTC, merged