#164046205 Setup React Router Version 4
andela/ah-legion-frontend pull request #3
Opened 2019-04-02 11:56 UTC by RachelleMaina

### What does this PR do?
It setups react router version 4.

### Description
Installs and configures the router by creating these folders: components, routes and css and these components: Header, Footer, Login and Home  in order to create a dummy route for login and the "/" page to test the configuration.

### How to manually test this
Clone the repo and checkout to this branch `ch-react-router-164046205`. Install the dependencies using `npm install` then start the app using `npm start`. On the browser you should see the navbar, a `Home` text and the footer. On the navbar, click `Login` to go to the Login component.

### PT
[#164046205](https://www.pivotaltracker.com/story/show/164046201)

2019-04-03 16:19 UTC, abulojoshua1 approved these changes
LGTM

2019-04-03 16:22 UTC, abulojoshua1 requested changes
I think `src/css/index.scss` should not be shown as a change in your PR, do you think it is possible to fix this.

2019-04-03 17:41 UTC, RachelleMaina commented
> I think `src/css/index.scss` should not be shown as a change in your PR, do you think it is possible to fix this.

Yes. It is possible.

2019-04-03 18:11 UTC, MandelaK commented on src/components/Header.js
> +          <NavLink to="/login" className="nav-link">
In our mockups, we have another link for registration on the navbar, I believe it's titled "Get started" ... could you please include it in this component?

2019-04-04 04:22 UTC, cob04 requested changes
I am getting this error 
`Module not found: Can't resolve './css/index.scss' in '/Users/cobain/Andela/tester/ah-legion-frontend/src'`

Please move `index.scss` into the `css` directory to resolve this.

2019-04-04 06:12 UTC, RachelleMaina commented on src/components/Header.js
> +          <NavLink to="/login" className="nav-link">
As per the PT story, I only had to add the "/" and "login "routes. I think this will be done on the registration PR

2019-04-04 06:15 UTC, RachelleMaina commented
> I am getting this error
> `Module not found: Can't resolve './css/index.scss' in '/Users/cobain/Andela/tester/ah-legion-frontend/src'`
> 
> Please move `index.scss` into the `css` directory to resolve this.

I do not think I am supposed to change that in this PR. I have however corrected the way it is imported. It should work now.

2019-04-05 08:42 UTC, MandelaK commented
@RachelleMaina why did you delete app.json? I believe it's used to set up our pipelines.

2019-04-05 08:53 UTC, RachelleMaina commented
> @RachelleMaina why did you delete `app.json`? I believe it's used to set up our pipelines.

I did not have an `app.json`. I did have an `App.js` though which was not necessary in its current location. I deleted that. I created` index.jsx` in the Routes/ directory which adds better functionality

2019-04-05 08:58 UTC, RachelleMaina commented
> @RachelleMaina why did you delete `app.json`? I believe it's used to set up our pipelines.

I see it's present in the develop branch. let me see what I have done wrong.

2019-04-05 09:00 UTC, RachelleMaina commented
> @RachelleMaina why did you delete `app.json`? I believe it's used to set up our pipelines.

I have corrected this.

2019-04-05 11:43 UTC, cob04 approved these changes
The routes work great.

2019-04-05 12:09 UTC, ElMonstro approved these changes
Approved

2019-04-05 12:13 UTC, MandelaK approved these changes

2019-04-05 12:14 UTC, Etomovich approved these changes

2019-04-05 12:14 UTC, BrianSerem approved these changes
What you have done here is good work, unless you add more changes, this is good to go.

2019-04-05 12:17 UTC, abulojoshua1 approved these changes
LGTM

2019-04-05 12:17 UTC, merged