chore(setup CircleCI): Enable continuous integration
andela/ah-legion-frontend pull request #9
Opened 2019-04-04 09:01 UTC by Etomovich

**Description**
<hr/>

This PR creates the configuration of Circle CI. It also adds configuration of Code Climate that checks code maintainability and test coverage.

**Type of Change**
<hr/>

- [x] chore(non-breaking change that makes continuous integration possible).

**Checklist**
- [x] Integration of CircleCI

**Related Stories**
[Continous Intergration with Circle CI](https://www.pivotaltracker.com/n/projects/2313280/stories/164046207)

2019-04-04 09:02 UTC, abulojoshua1 commented
@Etomovich, kindly add a label to this PR.

2019-04-04 09:03 UTC, Etomovich commented
> @Etomovich, kindly add a label to this PR.

Thanks for that @abulojoshua1. A slight oversight.

2019-04-04 09:08 UTC, BrianSerem approved these changes

2019-04-04 09:10 UTC, ElMonstro approved these changes

2019-04-04 09:12 UTC, MandelaK approved these changes

2019-04-04 09:13 UTC, RachelleMaina approved these changes
LGTM

2019-04-04 09:14 UTC, cob04 approved these changes
Circle Ci checks run fine.
Stubborn dependency `"eslint": "^5.16.0"` removed.

2019-04-05 08:20 UTC, abulojoshua1 requested changes

2019-04-05 08:20 UTC, abulojoshua1 commented on .gitignore
> +package-lock.json
@Etomovich, kindly add an EOF here.

2019-04-05 11:40 UTC, Etomovich commented on .gitignore
> +package-lock.json
Ok sorry for the delay

2019-04-05 12:18 UTC, abulojoshua1 approved these changes
LGTM

2019-04-05 12:18 UTC, merged